package report

import (
	"encoding/json"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"time"

	"github.com/hakanolgun/dependency-analyzer/cli-go/internal/engine"
)

func GenerateGoHTML(report *engine.GoProjectReport, outDir string) (string, error) {
	report.GeneratedAt = time.Now().Format(time.RFC3339)
	outPath := filepath.Join(outDir, "dependency-report.html")

	file, err := os.Create(outPath)
	if err != nil {
		return "", err
	}
	defer file.Close()

	data, err := buildGoHTMLData(report)
	if err != nil {
		return "", err
	}

	tpl := template.Must(template.New("goreport").Parse(goReportTemplate))

	if err := tpl.Execute(file, data); err != nil {
		return "", err
	}
	return outPath, nil
}

type goHTMLData struct {
	ProjectPath  string
	ModuleName   string
	GoVersion    string
	GeneratedAt  string
	ModuleCount  int
	ScannedCount int
	FailedCount  int
	Rows         []goHTMLRow
	ReportJSON   template.JS
}

type goHTMLRow struct {
	Name        string
	RepoURL     string
	ModuleErr   string
	CurrVersion string

	LatestVersion string
	HasLatest     bool

	LastPrimary   string
	LastSecondary string
	ShowLast      bool

	MaintainedClass string
	MaintainedText  string
	ShowMaintained  bool

	ReplaceShow   bool
	RepLabel      string
	RepLabelClass string
	Score         int
}

func buildGoHTMLData(r *engine.GoProjectReport) (goHTMLData, error) {
	d := goHTMLData{
		ProjectPath:  r.ProjectPath,
		ModuleName:   r.ModuleName,
		GoVersion:    r.GoVersion,
		GeneratedAt:  r.GeneratedAt,
		ModuleCount:  len(r.Dependencies),
		ScannedCount: r.ScannedCount,
		FailedCount:  r.FailedCount,
		Rows:         make([]goHTMLRow, 0, len(r.Dependencies)),
	}
	for _, dep := range r.Dependencies {
		d.Rows = append(d.Rows, goHTMLRowFrom(dep))
	}

	b, err := json.Marshal(r)
	if err != nil {
		return goHTMLData{}, fmt.Errorf("marshal go report JSON: %w", err)
	}
	d.ReportJSON = template.JS(b)

	return d, nil
}

func goHTMLRowFrom(dep engine.GoModuleResult) goHTMLRow {
	row := goHTMLRow{
		Name:        dep.Name,
		RepoURL:     dep.RepoURL,
		ModuleErr:   dep.Error,
		CurrVersion: dep.CurrentVersion,
	}

	if dep.LatestVersion != "" {
		row.LatestVersion = dep.LatestVersion
		row.HasLatest = true
	}

	if dep.TimeSinceLastUpdate != "" {
		row.LastPrimary = dep.TimeSinceLastUpdate
		if dep.LastUpdateDate != "" {
			if t, err := time.Parse(time.RFC3339Nano, dep.LastUpdateDate); err == nil {
				row.LastSecondary = t.Format("1/2/2006")
			} else {
				row.LastSecondary = dep.LastUpdateDate
			}
		}
		row.ShowLast = true
	}

	if dep.IsMaintained != "" {
		row.ShowMaintained = true
		row.MaintainedClass = maintainedBadgeClass(dep.IsMaintained)
		row.MaintainedText = maintainedDisplay(dep.IsMaintained)
	}

	if dep.Error == "" {
		row.ReplaceShow = true
		lbl, cls := replaceabilityTier(dep.Score)
		row.RepLabel = lbl
		row.RepLabelClass = cls
		row.Score = dep.Score
	}

	return row
}

const goReportTemplate = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Go Module Analysis – {{ .ProjectPath }}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
  <style>
` + embeddedReportCSS + `
  .badge.go {
    background: rgba(0, 173, 216, 0.2);
    color: #00add8;
  }
  </style>
</head>
<body>
  <div id="root">
    <div class="app-container">

      <!-- ── HEADER ─────────────────────────────────────────────── -->
      <div class="glass-panel header-panel">
        <h1 class="title">Dependency Analyzer</h1>
        <h2 class="subtitle repo-subtitle">
          <a href="https://github.com/hakanolgun/dependency-analyzer"
             target="_blank" rel="noreferrer" class="repo-link subtitle-link">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2"
                 stroke-linecap="round" stroke-linejoin="round">
              <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
            </svg>
          </a>
        </h2>
        <p class="subtitle">Offline report generated by the CLI tool</p>
      </div>

      <!-- ── RESULTS PANEL ──────────────────────────────────────── -->
      <div class="glass-panel">
        <div class="header-actions">
          <div>
            <h2 class="title" style="text-align:left;font-size:2rem;margin-bottom:0.2rem;">Analysis Complete</h2>
            <p class="subtitle" style="text-align:left;margin:0;">
              Analyzed {{ .ModuleCount }} modules
              <span class="badge go" style="margin-left:0.5rem;">Go Module</span>
            </p>
            <p class="subtitle" style="text-align:left;margin-top:0.5rem;font-size:0.9rem;">
              Module: {{ .ModuleName }} &middot; Go {{ .GoVersion }} &middot; Generated {{ .GeneratedAt }} &middot; Scanned {{ .ScannedCount }} &middot; Failed {{ .FailedCount }}
            </p>
          </div>
          <div style="display:flex;gap:0.5rem;flex-shrink:0;">
            <button id="btn-download" class="btn" style="background:rgba(255,255,255,0.1);">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none"
                   stroke="currentColor" stroke-width="2"
                   stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                <polyline points="7 10 12 15 17 10"></polyline>
                <line x1="12" y1="15" x2="12" y2="3"></line>
              </svg>
              Export JSON
            </button>
          </div>
        </div>

        <div class="table-container">
          <table id="results-table">
            <thead>
              <tr>
                <th data-col="name" class="sortable">
                  Module Name <span class="sort-icon" data-for="name"></span>
                </th>
                <th>Your Version</th>
                <th>Latest Version</th>
                <th data-col="lastUpdateDate" class="sortable">
                  Last Update <span class="sort-icon" data-for="lastUpdateDate"></span>
                </th>
                <th data-col="isMaintained" class="sortable">
                  Maintained <span class="sort-icon" data-for="isMaintained"></span>
                </th>
                <th data-col="score" class="sortable">
                  Replaceability <span class="sort-icon" data-for="score"></span>
                </th>
              </tr>
            </thead>
            <tbody id="results-body">
            {{ range .Rows }}
              <tr>
                <td>
                  <div class="pkg-name">
                    {{ if .RepoURL }}
                      <a href="{{ .RepoURL }}" target="_blank" rel="noreferrer" class="repo-link" title="{{ .RepoURL }}">{{ .Name }} <span class="ext">↗</span></a>
                    {{ else }}
                      <span style="word-break:break-all;">{{ .Name }}</span>
                    {{ end }}
                  </div>
                  {{ if .ModuleErr }}
                    <span class="pkg-err">{{ .ModuleErr }}</span>
                  {{ end }}
                </td>
                <td><span class="badge gray">{{ .CurrVersion }}</span></td>
                <td>
                  {{ if .HasLatest }}<span class="badge info">{{ .LatestVersion }}</span>{{ else }}<span class="muted">-</span>{{ end }}
                </td>
                <td>
                  {{ if .ShowLast }}
                    <div class="stack">
                      <span>{{ .LastPrimary }}</span>
                      <span class="sub">{{ .LastSecondary }}</span>
                    </div>
                  {{ else }}
                    <span class="muted">-</span>
                  {{ end }}
                </td>
                <td>
                  {{ if .ShowMaintained }}
                    <span class="badge {{ .MaintainedClass }}">{{ .MaintainedText }}</span>
                  {{ else }}
                    <span class="muted">-</span>
                  {{ end }}
                </td>
                <td class="cell-replace">
                  {{ if .ReplaceShow }}
                    <div class="replace-stack">
                      <span class="badge {{ .RepLabelClass }}">{{ .RepLabel }}</span>
                      <span class="sub">{{ .Score }}/100</span>
                    </div>
                  {{ else }}
                    <span class="muted">-</span>
                  {{ end }}
                </td>
              </tr>
            {{ end }}
            </tbody>
          </table>
        </div>
      </div>

      <!-- ── MAINTENANCE LEGEND ─────────────────────────────────── -->
      <div class="maintenance-legend-section">
        <div class="legend-container">
          <h3 class="legend-title">Maintenance Status Key</h3>
          <div class="legend-grid">
            <div class="legend-item">
              <div class="legend-badge badge-yes"><span class="lg-ico">&#10003;</span><span>Yes</span></div>
              <p class="legend-description">The module is active, has recent updates, and is not abandoned.</p>
            </div>
            <div class="legend-item">
              <div class="legend-badge badge-unlikely"><span class="lg-ico">&#9888;</span><span>Unlikely</span></div>
              <p class="legend-description">No updates in the last 2 years. The module might be abandoned.</p>
            </div>
          </div>
        </div>
      </div>

      <!-- ── REPLACEABILITY LEGEND ──────────────────────────────── -->
      <div class="maintenance-legend-section">
        <div class="legend-container">
          <h3 class="legend-title">Replaceability Score</h3>
          <p class="legend-description" style="text-align:center;">
          Replaceability Score measures how difficult it would be to replace a particular dependency in your project. A higher score indicates that removing or replacing the dependency would require significant effort and could introduce risk.
          </p>
          <div class="legend-grid">
            <div class="legend-item">
              <div class="legend-badge badge-yes"><span class="lg-ico">&#9679;</span><span>Easy (0-30)</span></div>
              <p class="legend-description">Mostly small and straightforward modules with low complexity.</p>
            </div>
            <div class="legend-item">
              <div class="legend-badge badge-unlikely"><span class="lg-ico">&#9888;</span><span>Medium (31-70)</span></div>
              <p class="legend-description">Moderate logic and dependency coupling. Replacement is possible with focused effort.</p>
            </div>
            <div class="legend-item">
              <div class="legend-badge badge-no"><span class="lg-ico">&#10007;</span><span>Hard (71-100)</span></div>
              <p class="legend-description">CGO bindings, broad API surface, or complex internals make replacement difficult.</p>
            </div>
          </div>
        </div>
      </div>

      <!-- ── FOOTER ─────────────────────────────────────────────── -->
      <footer class="footer glass-panel">
        <h3 class="footer-title">Author</h3>
        <div class="author-container">
          <img src="https://github.com/hakanolgun.png" alt="Hakan Olgun" class="author-avatar" />
          <div class="author-details">
            <span class="author-name">Hakan Olgun</span>
            <div class="social-links">
              <a href="https://github.com/hakanolgun" target="_blank" rel="noreferrer" title="GitHub">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                  <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
                </svg>
              </a>
              <a href="https://linkedin.com/in/hknlgn" target="_blank" rel="noreferrer" title="LinkedIn">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                  <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path>
                  <rect x="2" y="9" width="4" height="12"></rect>
                  <circle cx="4" cy="4" r="2"></circle>
                </svg>
              </a>
              <a href="https://x.com/kpt_hkn" target="_blank" rel="noreferrer" title="X (Twitter)">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                  <path d="M4 4l11.733 16h4.267l-11.733-16z"></path>
                  <path d="M4 20l6.768-6.768m2.46-2.46l6.772-6.772"></path>
                </svg>
              </a>
              <a href="https://social.vivaldi.net/@mathrandom" target="_blank" rel="noreferrer" title="Mastodon" class="mastodon-icon">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2"
                     stroke-linecap="round" stroke-linejoin="round">
                  <path d="M21.58 13.913c-.245 3.074-2.81 5.9-6.31 6.551-2.146.398-4.4.453-6.195.148-1.52-.259-2.85-.92-2.85-.92s-.027-1.393-.049-2.924c1.238.384 2.658.544 4.148.514 2.805-.054 4.978-.507 5.679-2.079.034-.078.066-.159.096-.24.593-1.68-.041-3.666-.041-3.666-4.636 1.139-8.497.106-9.67-2.613-.245-.583-.34-1.282-.365-2.008-.045-1.196-.062-2.52.016-3.834.135-2.261 1.258-4.502 3.619-5.496C11.597 2.456 14.542 2.5 14.542 2.5h.063s2.946-.044 4.256.848c2.361.993 3.484 3.235 3.619 5.496.113 1.956.12 4.17.065 6.069h-.963z" />
                  <path d="M16.51 10.74v.85h-1.57v-.85c0-1.07-.63-1.6-1.89-1.6-1.37 0-2.06.67-2.06 2.01v4.4h-1.54v-4.4c0-1.34-.69-2.01-2.06-2.01-1.26 0-1.89.53-1.89 1.6v.85H3.93v-1.63c0-1.57.85-2.6 2.53-3.1.55-.16 1.16-.24 1.83-.24 1.25 0 2.21.36 2.89 1.07.67-.71 1.63-1.07 2.89-1.07.67 0 1.28.08 1.83.24 1.68.5 2.53 1.53 2.53 3.1v1.63z" />
                </svg>
              </a>
            </div>
          </div>
        </div>
      </footer>

    </div><!-- /.app-container -->
  </div><!-- /#root -->

  <!-- ── EMBEDDED REPORT DATA ───────────────────────────────────── -->
  <script>
    var REPORT_DATA = {{ .ReportJSON }};
  </script>

  <!-- ── CLIENT-SIDE INTERACTIVITY ─────────────────────────────── -->
  <script>
  (function () {
    'use strict';

    var sortKey = null;
    var sortDir = 'desc';

    var maintainedWeight = { yes: 3, unlikely: 2, no: 1 };

    function valueOf(dep, key) {
      switch (key) {
        case 'name':            return (dep.name || '').toLowerCase();
        case 'lastUpdateDate':  return dep.lastUpdateDate ? new Date(dep.lastUpdateDate).getTime() : 0;
        case 'isMaintained':    return maintainedWeight[dep.isMaintained] || 0;
        case 'score':           return dep.score != null ? dep.score : -1;
        default:                return 0;
      }
    }

    function sortedDeps() {
      var deps = REPORT_DATA.dependencies.slice();
      if (!sortKey) return deps;
      deps.sort(function (a, b) {
        var va = valueOf(a, sortKey);
        var vb = valueOf(b, sortKey);
        if (va < vb) return sortDir === 'asc' ? -1 : 1;
        if (va > vb) return sortDir === 'asc' ?  1 : -1;
        return 0;
      });
      return deps;
    }

    function maintainedBadge(status) {
      if (!status) return '<span class="muted">-</span>';
      var cls = status === 'yes' ? 'success' : status === 'unlikely' ? 'warning' : 'danger';
      var txt = status === 'yes' ? 'Yes' : status === 'unlikely' ? 'Unlikely' : 'No';
      return '<span class="badge ' + cls + '">' + txt + '</span>';
    }

    function replaceabilityCell(dep) {
      if (dep.error) return '<span class="muted">-</span>';
      var score = dep.score != null ? dep.score : 0;
      var label, cls;
      if (score >= 71)      { label = 'Hard';   cls = 'danger'; }
      else if (score >= 31) { label = 'Medium'; cls = 'warning'; }
      else                  { label = 'Easy';   cls = 'success'; }

      return '<div class="replace-stack">' +
        '<span class="badge ' + cls + '">' + label + '</span>' +
        '<span class="sub">' + score + '/100</span>' +
        '</div>';
    }

    function escapeHTML(s) {
      return String(s)
        .replace(/&/g,'&amp;').replace(/</g,'&lt;')
        .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    }

    function formatDate(dep) {
      if (!dep.timeSinceLastUpdate) return '<span class="muted">-</span>';
      var secondary = '';
      if (dep.lastUpdateDate) {
        var d = new Date(dep.lastUpdateDate);
        secondary = (d.getMonth()+1) + '/' + d.getDate() + '/' + d.getFullYear();
      }
      return '<div class="stack"><span>' + escapeHTML(dep.timeSinceLastUpdate) + '</span>' +
             (secondary ? '<span class="sub">' + secondary + '</span>' : '') + '</div>';
    }

    function renderBody() {
      var deps = sortedDeps();
      var rows = deps.map(function (dep) {
        var namecell;
        if (dep.repoUrl) {
          namecell = '<a href="' + escapeHTML(dep.repoUrl) + '" target="_blank" rel="noreferrer" class="repo-link" title="' + escapeHTML(dep.repoUrl) + '">' +
                     escapeHTML(dep.name) + ' <span class="ext">↗</span></a>';
        } else {
          namecell = '<span style="word-break:break-all;">' + escapeHTML(dep.name) + '</span>';
        }
        var errCell = dep.error ? '<span class="pkg-err">' + escapeHTML(dep.error) + '</span>' : '';

        var latestCell = dep.latestVersion
          ? '<span class="badge info">' + escapeHTML(dep.latestVersion) + '</span>'
          : '<span class="muted">-</span>';

        return '<tr>' +
          '<td><div class="pkg-name">' + namecell + '</div>' + errCell + '</td>' +
          '<td><span class="badge gray">' + escapeHTML(dep.currentVersion) + '</span></td>' +
          '<td>' + latestCell + '</td>' +
          '<td>' + formatDate(dep) + '</td>' +
          '<td>' + maintainedBadge(dep.isMaintained) + '</td>' +
          '<td class="cell-replace">' + replaceabilityCell(dep) + '</td>' +
          '</tr>';
      });
      document.getElementById('results-body').innerHTML = rows.join('');
    }

    function renderSortIcons() {
      document.querySelectorAll('.sort-icon').forEach(function (el) {
        var col = el.getAttribute('data-for');
        if (col === sortKey) {
          el.textContent = sortDir === 'asc' ? ' ↑' : ' ↓';
        } else {
          el.textContent = '';
        }
      });
    }

    document.querySelectorAll('th[data-col]').forEach(function (th) {
      th.addEventListener('click', function () {
        var col = th.getAttribute('data-col');
        if (sortKey === col) {
          if (sortDir === 'asc') {
            sortDir = 'desc';
          } else {
            sortKey = null;
          }
        } else {
          sortKey = col;
          sortDir = 'asc';
        }
        renderSortIcons();
        renderBody();
      });
    });

    document.getElementById('btn-download').addEventListener('click', function () {
      var timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      var payload = {
        generatedAt: new Date().toISOString(),
        ecosystem: 'go',
        sort: { key: sortKey, direction: sortDir },
        results: sortedDeps()
      };
      var blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
      var url = URL.createObjectURL(blob);
      var a = document.createElement('a');
      a.href = url;
      a.download = 'go-analysis-' + timestamp + '.json';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    });

    renderSortIcons();

  })();
  </script>
</body>
</html>
`
